# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
name: fireflies
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongo-db

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data:
   driver: local