# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
name: fireflies
services:
  server:
    build:
      context: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URL=$MONGO_URL
      - MONGO_DATABASE=$MONGO_DATABASE
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - 3000:3000
    networks:
      - server-app
    depends_on:
      - mongo-db
    stdin_open: true
    tty: true

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - server-app
    volumes:
      - db-data:/data/db

volumes:
  db-data:
   driver: local

networks:
  server-app:
